/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_QUERY_VALIDATOR_C__
#define __RUST_QUERY_VALIDATOR_C__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef enum FfiChainType
#else
typedef uint8_t FfiChainType_t; enum
#endif
{
    /** . */
    FFI_CHAIN_TYPE_SUI = 0,
    /** . */
    FFI_CHAIN_TYPE_EVM = 1,
}
#ifdef DOXYGEN
FfiChainType_t
#endif
;


#include <stdbool.h>

typedef struct FfiValidationResult {

    bool is_error;

    char * message;

} FfiValidationResult_t;

FfiValidationResult_t ffi_validate (
    FfiChainType_t chain,
    char const * query);

void ffi_drop_validation_result (
    FfiValidationResult_t result);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_QUERY_VALIDATOR_C__ */
