mod assembly_script;
pub mod incident;
pub mod sql;

use crate::{
    daemon::{assembly_script::AssemblyScriptExecutor, incident::Incident, sql::SqlExecutor},
    BlockchainDataCtx, DataError, IncidentData,
};
use async_trait::async_trait;
use std::{collections::HashMap, fmt::Debug};

#[derive(Debug)]
pub struct VerifyCtx {
    /// Do daemon found any incidents.
    pub matched: bool,

    /// Incidents generated by the daemon expression.
    pub incidents: Vec<Incident>,
}

/// The parameters that are passed to Daemon.
pub type DaemonParameters = HashMap<String, String>;

/// An entity that can search Incidents in the [`BlockchainDataCtx`].
#[async_trait]
pub trait Executor: Send + Sync + Debug {
    /// Executes the given daemon.
    async fn execute(&self, ctx: &BlockchainDataCtx) -> Result<Vec<Incident>, DataError>;
}

/// The Daemon entity.
#[derive(Debug)]
pub struct Daemon {
    id: String,
    executor: Box<dyn Executor>,
}

impl Daemon {
    pub fn new_sql(
        id: String,
        expression: &str,
        incident_data: IncidentData,
    ) -> Result<Self, DataError> {
        let executor = Box::new(SqlExecutor::new(expression, incident_data)?);

        Ok(Self::new(id, executor))
    }

    pub fn new_assembly_script(
        id: String,
        wasm: impl AsRef<[u8]>,
        parameters: DaemonParameters,
    ) -> Result<Self, DataError> {
        let executor = Box::new(AssemblyScriptExecutor::new(wasm, parameters)?);

        Ok(Self::new(id, executor))
    }

    pub fn new(id: String, executor: Box<dyn Executor>) -> Self {
        Self { id, executor }
    }

    pub fn id(&self) -> String {
        self.id.clone()
    }

    /// Executes the given daemon.
    #[tracing::instrument(skip(ctx, self), fields(daemon_id = self.id(), tx_hash = ctx.tx_hash(), level = "trace"))]
    pub async fn verify(&self, ctx: &BlockchainDataCtx) -> Result<VerifyCtx, DataError> {
        let incidents = self.executor.execute(ctx).await?;

        Ok(VerifyCtx {
            matched: !incidents.is_empty(),
            incidents,
        })
    }
}
